### PR TITLE
Update status of shim to note that it has been on hold

### PR DESCRIPTION
**Pull request by jeffkaufman**

### CODE REVIEW

**Review by taymonbeal — CHANGES_REQUESTED** [review]
CI failure, please fix.

Also, should we archive the project after merging this?

**Comment by jeffkaufman** [comment]
@taymonbeal I agree that we should archive it.

I get the same CI failure running locally on main:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/bin/node',
1 verbose cli   '/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'check-format'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'precheck-format', 'check-format', 'postcheck-format' ]
5 info lifecycle @~precheck-format: @
6 info lifecycle @~check-format: @
7 verbose lifecycle @~check-format: unsafe-perm in lifecycle true
8 verbose lifecycle @~check-format: PATH: /usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/google/home/jefftk/code/fledge-polyfill/node_modules/.bin:/usr/local/google/home/jefftk/bin:/usr/local/google/home/jefftk/gems/bin:/usr/local/google/home/jefftk/.yarn/bin:/usr/local/google/home/jefftk/.config/yarn/global/node_modules/.bin:/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @~check-format: CWD: /usr/local/google/home/jefftk/code/fledge-polyfill
10 silly lifecycle @~check-format: Args: [ '-c', 'prettier --check .' ]
11 silly lifecycle @~check-format: Returned: code: 1  signal: null
12 info lifecycle @~check-format: Failed to exec check-format script
13 verbose stack Error: @ check-format: `prettier --check .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd /usr/local/google/home/jefftk/code/fledge-polyfill
16 verbose Linux 5.10.46-5rodete1-amd64
17 verbose argv "/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/bin/node" "/usr/local/google/home/jefftk/.nvm/versions/node/v12.16.3/bin/npm" "run" "check-format"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ check-format: `prettier --check .`
22 error Exit status 1
23 error Failed at the @ check-format script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Since we're going to archive, I think we should just ignore the CI, merge, and then archive?

**Comment by taymonbeal** [comment]
Branch is protected, so ignoring the CI requires some annoying reconfiguration. I checked offline and the problem is that you've got a double space after the first sentence and Prettier wants you to use a single space instead. If you fix that then it should work.

**Review by taymonbeal — APPROVED** [review]

**Comment by jeffkaufman** [comment]
Thanks, fixed! Looking closer at my local error it looks like it was actually complaining that `prettier` wasn't installed.

**Pull request merged**
